config/routes.rb
Rails.application.routes.draw do
    resources :happenings

    root to: "happenings#index"

end

app/models/happening.rb
class Happening < ActiveRecord::Base
    validates :name, presence:true, uniqueness:true
    validates :date, presence:true

    default_scope {order("date ASC")}

    def get_countdown_string
        @differenceInSeconds = date.to_time - DateTime.now().to_time
        if @differenceInSeconds > 0
            if get_days > 0
                return "#{get_days} d, #{get_hours} h, #{get_minutes} m"
            elsif get_hours > 0
                return "#{get_hours} h, #{get_minutes} m"
            elsif get_minutes > 0
                return "#{get_minutes} m"
            end 
        else
            return "completed"
        end
    end

    def get_minutes
        differenceInMinutes = @differenceInSeconds/60
        return minutes = (differenceInMinutes % 60).floor
    end

    def get_hours
        differenceInHours = @differenceInSeconds/60/60
        return hours = (differenceInHours % 24).floor
    end

    def get_days
        differenceInHours = @differenceInSeconds/60/60
        return days = (differenceInHours / 24).floor
    end

    def get_html_date 
        date.frmt_YY_mm_dd_HH_MM('--T:', true)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/happenings_controller.rb
class HappeningsController < ApplicationController
    
    before_action :find_happenings, only: [:index, :edit]
    before_action :set_variables, only: [:create]
    before_action :find_happening, only: [:edit, :update, :destroy]
    
    def set_variables
        @name = params[:name]
        @time = params[:date].to_datetime
    end

    def find_happening
        @happening = Happening.find(params[:id])
    end
    
    def find_happenings
        @happenings = Happening.all
    end

    def index
        puts @happenings.first.get_html_date
    end

    ##Use Javascript on the front end to figure out the correct time to display, based on the user's browser
    def setTimeZone
        @localTime = params[:time]
    end

    #Save the happening data in the database
    def create
        Happening.create(name: @name, date: @time)
        redirect_to root_path
    end

    def edit
    end

    def update
        @happening.update_attributes(params.require(:happening).permit([:name, :date]))
        redirect_to root_path
    end

    def destroy
        @happening.delete
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/happenings_helper.rb
module HappeningsHelper
end

app/views/happenings/_add.html.erb
<p>
<%= flash[:notice] %>
<h3>New Countdown</h3>
<form method="post" action="/happenings">
  <input id="new-counter" class="eventInput" type="text" name="name">
  <button type="submit" class="addButton">Add</button>
  <input type="datetime-local" id="new-date" name="date">
</form>
</p>

app/views/happenings/_label.html.erb
<li><label class="eventLabel"><%= happening.name%></label>
<%= button_to "Edit", edit_happening_path(happening), method: :get, class:"editButton"%>
<%= button_to "Delete", happening, method: :delete, class:"deleteButton"%>
<label class="counterLabel"><%= happening.get_countdown_string %></label>

app/views/happenings/_update.html.erb
<li>
<%=form_for(happening, :html => {:class => 'update'}) do |f|%>
    <%=f.text_field :name, class:"updateInput" %>
    <%=f.submit "Save", class:"editButton" %>
    <%=f.datetime_local_field :date %>
<%end%>
<%= button_to "Delete", happening, method: :delete, class:"deleteButton"%>
</li>   

app/views/happenings/edit.html.erb
<%=render "add"%>
<h3>Running countdowns</h3>
<ul id="running-countdowns">
<%#<li><label class="eventLabel">Event</label><input class="eventInput" type="text">%>
<%#<button class="editButton">Edit</button><button class="deleteButton">Delete</button>%>
<%#<label class="counterLabel">21d, 17h, 35min</label><input type="datetime-local" value="2015-12-19T16:39"></li>%>
<% @happenings.each do |happening| %>
    <%puts happening%>
    <% if happening.get_countdown_string != "completed"%>
        <%if happening.id == @happening.id %>
            <%=render "update", happening: happening%>
        <%else%>
            <%=render "label", happening: happening%>
        <%end%>
    <%end%>
<% end %>
</ul>

<h3>Completed countdowns</h3>
<ul id="completed-countdowns">
<% @happenings.each do |happening| %>
    <% if happening.get_countdown_string == "completed"%>
        <%if happening.id == @happening.id %>
            <%=render "update", happening: happening%>
        <%else%>
            <%=render "label", happening: happening%>
        <%end%>
    <% end %>
<% end %>
</ul>
<script src="http://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript" charset="utf-8"></script>

app/views/happenings/index.html.erb
<%=render "add"%>
<h3>Running countdowns</h3>
<ul id="running-countdowns">
<% @happenings.each do |happening| %>
    <% if happening.get_countdown_string != "completed"%>
        <%=render "label", happening: happening%>
    <%end%>
<% end %>
</ul>

<h3>Completed countdowns</h3>
<ul id="completed-countdowns">
<% @happenings.each do |happening| %>
    <% if happening.get_countdown_string == "completed"%>
        <%=render "label", happening: happening%>
    <% end %>
<% end %>
</ul>
<script src="http://code.jquery.com/jquery-1.11.0.min.js" type="text/javascript" charset="utf-8"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CountdownRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="page-wrap">

    <%if flash[:notice]%>
        <p> <%= flash[:notice] %> </p>
    <%end%>
    
<div class="container">
    <%= yield %>
</div>
</div>
</body>
<footer>
&copy; 2015 Simon Buysse
</footer>
</html>